
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorResource", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorResource {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://Service/", className = "service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://Service/", className = "service.AddResponse")
    @Action(input = "http://Service/CalculatorResource/addRequest", output = "http://Service/CalculatorResource/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://Service/", className = "service.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://Service/", className = "service.MulResponse")
    @Action(input = "http://Service/CalculatorResource/mulRequest", output = "http://Service/CalculatorResource/mulResponse")
    public double mul(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://Service/", className = "service.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://Service/", className = "service.DivResponse")
    @Action(input = "http://Service/CalculatorResource/divRequest", output = "http://Service/CalculatorResource/divResponse")
    public double div(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://Service/", className = "service.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://Service/", className = "service.SubResponse")
    @Action(input = "http://Service/CalculatorResource/subRequest", output = "http://Service/CalculatorResource/subResponse")
    public double sub(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
